# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_PROD_ENV: ${{ secrets.SERVER_PROD_ENV }}
      WEB_PROD_ENV: ${{ secrets.WEB_PROD_ENV }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: echo "${SERVER_PROD_ENV}" | base64 --decode > "./apps/server/.env"
      - run: echo "${WEB_PROD_ENV}" | base64 --decode > "./apps/web/.env.production.local"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm build
